name: Unzip and Commit

on:
  push:
    paths:
      - "educenter-bootstrap-main.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip File
        run: unzip educenter-bootstrap-main.zip -d educenter-bootstrap-main

      - name: Commit and Push Unzipped Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add educenter-bootstrap-main/
          git commit -
